version: '3.8'
services:

  # Postgres service
  # Add username and password for the postgres database in POSTGRES_URL in postgres and POSTGRES_URI down in services
  postgres:
    environment: 
      POSTGRES_USER: username
      POSTGRES_PASSWORD: pwd
      POSTGRES_URL: postgres://admin:pwd@localhost:5432/smart-brain
      POSTGRES_DB: smart-brain
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"

  # Backend Server     
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment : 
      POSTGRES_URI : postgres://admin:pwd@postgres:5432/smart-brain
      REDIS_URI : redis://redis:6379
    ports:
      - "4000:4000"
    volumes:
      - ./ : /usr/src/smart-brain-api